### ISSUE TITLE
primo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/ifelse#3]
Scrivi un programma che trovi la soluzione a equazioni di primo grado
nella forma ax+b=0, con a e b interi.

Il programma dovrebbe tener conto dei casi particolari: a, b o entrambi nulli.

**Comment by luca998** [comment]
perchè mi dà errore ad else if?

**Comment by FabioZTessitore** [comment]
elif

**Comment by FabioZTessitore** [comment]
ancora problemi?

**Comment by luca998** [comment]
si,come faccio a fargli fare la divisione e ad ottenere il quoziente decimale?

**Comment by FabioZTessitore** [comment]
spiegati meglio

**Comment by luca998** [comment]
devo fare la divisione -a/b e voglio che il risultato sia decimale non intero

**Comment by FabioZTessitore** [comment]
ok, ma tu sai che la divisione tra interi da come risultato un intero

**Comment by luca998** [comment]
si quindi devo per forza dichiarare a e b float?

**Comment by FabioZTessitore** [comment]
solo che in python le variabili non si dichiarano

**Comment by luca998** [comment]
si scrivono e basta

**Comment by FabioZTessitore** [comment]
appunto, quindi devi trovare un altro metodo per ottenere un'operazione tra float

**Comment by luca998** [comment]
scrivo che sono float nell'operazione che mi interessa?

**Comment by FabioZTessitore** [comment]
vediamo

**Comment by luca998** [comment]
ok caricato, ho cancellato i file con ~ perchè il .gitignore non funzionava e l'ho rifatto

**Comment by FabioZTessitore** [comment]
va bene però l'espressione `float (-b)/(a)` trasforma in float solo `b`. Poi per poter effettuare l'operazione tra un float e un int anche `a` viene trasformato in float. Chiaro?
Passiamo a quelle di secondo grado

**Comment by luca998** [comment]
Ok chiaro
