### ISSUE TITLE
secondo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/ifelse#4]
Scrivi un programma che trovi le soluzioni a equazioni di secondo grado
nella forma ax^2+bx+c=0, con a, b e c interi.
Il programma dovrebbe tener conto dei casi particolari.

Per il calcolo della radice quadrata si puo' utilizzare la funzione `sqrt()`
della libreria matematica math

``` python
import math

... math.sqrt() ...
```

**Comment by luca998** [comment]
l'allineamento degli if o else in python è diverso dal c++
